version: 2
jobs:
  build:
    working_directory: /go/src/github.com/segmentio/events

    docker:
      - image: circleci/golang

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true
          docker_layer_caching: true

      - run:
          name: Install Dependencies
          command: go get -v ./...

      - run:
          name: Vet
          command: go vet ./...

      - run:
          name: Test
          command: go test -v -race ./...
